# Add the port your service shall run on in here.
management:
  endpoints:
    web:
      exposure:
        include: "*" # provide all management endpoints per http (for development/testing only)

server:
  shutdown: immediate # for local development, don't wait until all requests are done

# Set logging levels by package names
logging:
  level:
    com.tipico.services.talimitservice: DEBUG
